### ISSUE TITLE
Incompatible with Python3.10

### ISSUE THREAD

**Issue by thelicato** [deepmind/android_env#28] opened 2022-07-06 08:46 UTC
I tried to install ``android_env`` both from **pip** and source code but I get an error on install. Digging a little more I found out that the installed version of ``numpy`` (which is **1.19.5**) is incompatible with Python3.10. 

For now I removed the version requirement from *setup.py* and the installation completed successfully.

**Comment by kenjitoyama** [comment] 2022-08-09 18:02
Hi @thelicato, is this still an issue? We now require `numpy` [`>=1.21`](https://github.com/deepmind/android_env/blob/main/setup.py#L114).

Later I can try adding Py `3.10` to our automation tests.

**Comment by kenjitoyama** [comment] 2022-11-11 17:36
It looks like Python 3.10 is working as intended. Please see https://github.com/deepmind/android_env/pull/98.

I'll close this for now.

**Closed by kenjitoyama** 2022-11-11 17:36 UTC
